package com.opencode.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TspWorkMessage generated by MyEclipse - Hibernate Tools
 */
public class TspWorkMessage extends AbstractTspWorkMessage implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TspWorkMessage() {
    }

	/** minimal constructor */
    public TspWorkMessage(Long messId, String messTitle, String messFlag, String messIsStaste, String messIncUser, String messAppUser, Date messAppDate, String messDeptCode, String messTableCode, Long messTableId) {
        super(messId, messTitle, messFlag, messIsStaste, messIncUser, messAppUser, messAppDate, messDeptCode, messTableCode, messTableId);        
    }
    
    /** full constructor */
    public TspWorkMessage(Long messId, String messTitle, String messContent, String messFlag, String messIsStaste, String messIncUser, String messAppUser, Date messAppDate, String messDeptCode, String messTableCode, Long messTableId) {
        super(messId, messTitle, messContent, messFlag, messIsStaste, messIncUser, messAppUser, messAppDate, messDeptCode, messTableCode, messTableId);        
    }
   
}
